config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#home'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  post 'logout' => 'session#destroy'

  get '/auth/facebook/callback' => 'session#create_from_facebook'

  get '/lessons/physics' => 'lessons#physics'

  resources :users, only: [:show] do
    resources :lessons, only: [:show, :index, :new, :create]
  end

  resources :lessons

  post 'lessons/:id/book' => 'lessons#book', as: "book"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    # has_many :lesson_students, foreign_key: :taken_lesson_id
    # has_many :students, through: :lesson_students
    # belongs_to :instructor, class_name: "User"
    validates :subject, presence: true
    validates :location, presence: true
    validates :time, presence: true
    validates :duration, presence: true
    scope :available, -> { where("booked == false") }

    belongs_to :instructor, class_name: "User"
    belongs_to :student, class_name: "User", optional: true

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    scope :instructors, -> { where("instructor == true") }
    scope :students, -> { where("instructor == false") }

    # has_many :lesson_students, foreign_key: :lesson_student_id
    # has_many :taken_lessons, through: :lesson_students
    # has_many :given_lessons, foreign_key: :instructor_id, class_name: "Lesson"

    # instructor associations
    has_many :given_lessons, foreign_key: "instructor_id", class_name: "Lesson"
    has_many :students, through: :given_lessons

    # student associations
    has_many :taken_lessons, foreign_key: "student_id", class_name: "Lesson"
    has_many :instructors, through: :taken_lessons

    def student?
        !self.instructor
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    # before_action :verified_user
    helper_method :current_user
    helper_method :user_is_authenticated
    helper_method :belongs_to_current_user
    helper_method :user_is_instructor
    before_action :require_login

    private

    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def user_is_authenticated
        !!current_user
    end

    def user_is_instructor
        current_user.instructor
    end

    def require_login
        redirect_to root_path unless user_is_authenticated
    end

    def user_root_redirect
        if current_user.instructor
            redirect_to user_lessons_path(current_user)
        else
            redirect_to user_path(current_user)
        end
    end

    def belongs_to_current_user(lesson)
        lesson.instructor_id == current_user.id
    end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    before_action :set_lesson, only: [:show, :edit, :update, :destroy, :book]
    # before_action :protect_new_lesson, only: [:new, :create]
    before_action :protect_lesson, only: [:edit, :update]


    def new
        @lesson = Lesson.new
    end

    def create
        @lesson = Lesson.new(lesson_params)
        @lesson.instructor = current_user
        if @lesson.save
            change_status
            redirect_to lesson_path(@lesson)
        else
            render :new
        end
    end

    def show
        
    end

    def index
        if params[:user_id] && @user = User.find_by(id: params[:user_id])
            if !@user.instructor
                redirect_to user_path(current_user)
            end
            @lessons = @user.given_lessons.available
        else
            @lessons = Lesson.available
        end
    end

    def edit

    end

    def update
        if @lesson.update(lesson_params)
            change_status
            redirect_to lesson_path(@lesson)
        else
            render :edit
        end
    end

    def destroy
        @lesson.destroy
        redirect_to user_path(current_user)
    end

    def book
        if !current_user.instructor
            @lesson.student = current_user
            change_status
            @lesson.save
        end
        redirect_to lesson_path(@lesson)
    end

    def physics
        @lessons = Lesson.available.select do |l| 
            l.subject.include?("hysics")
        end
        render "lessons/physics"

    end

    private

    def lesson_params
        params.require(:lesson).permit(:subject, :location, :time, :duration, :notes, :student_id)
    end

    def set_lesson
        @lesson = Lesson.find_by(id: params[:id])
        if !@lesson
            redirect_to lessons_path
        end
    end

    def change_status
        if @lesson.student
            @lesson.booked = true
            @lesson.save
        end
    end

    def protect_lesson
        if @lesson.instructor_id != current_user.id
            redirect_to lesson_path(@lesson)
        end
    end

    def protect_new_lesson
        if params[:user_id] && current_user.id != params[:user_id] || !current_user.instructor
            redirect_to lessons_path
        end
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    skip_before_action :require_login, only: [:new, :create, :create_from_facebook]

    def new
        if current_user
            redirect_to user_path(current_user)
        end
        @user = User.new
    end

    def create
        @user = User.find_by(name: params[:user][:name])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(current_user)
        else
            @user = User.new
            @user.errors.messages[:invalid] = ["username or password"]
            render :new
        end
    end

    def create_from_facebook
        @user = find_or_create_from_facebook
        session[:user_id] = @user.id
        redirect_to user_path(current_user)
    end

    def destroy
        session.delete :user_id
        redirect_to root_path
    end

    private

    def auth
        request.env['omniauth.auth']
    end

    def find_or_create_from_facebook
        User.find_or_create_by(email: auth[:info][:email]) do |u|
            u.name = auth[:info][:name]
            u.email = auth[:info][:email]
            u.password = ('a'..'z').to_a.shuffle[0,8].join
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        
    end

    def create

    end

    def destroy

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]

    def show
        @user = User.find_by(id: params[:id])
        if !@user
            redirect_to lessons_path
        end
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :password, :email, :instructor)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    skip_before_action :require_login

    def home
        if user_is_authenticated
            redirect_to user_path(current_user)
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/lessons_helper.rb
module LessonsHelper
    def time_slot_display(lesson)
        finish = (lesson.time + 60*lesson.duration).strftime("%l:%M %p")
        lesson.time.strftime("%A, %b %d %Y from %l:%M %p to #{finish}")
    end

    def lesson_show_page_button(lesson)
        if belongs_to_current_user(lesson)
            link_to "edit lesson", edit_lesson_path(lesson), class: "btn btn-success btn-lg"
        elsif current_user.student? && !lesson.booked
            link_to "book lesson", book_path(lesson), method: "post", class: "btn btn-success btn-lg"
        end
    end

    def status(lesson)
        if lesson.time.past?
            "completed"
        elsif lesson.student
            "booked"
        else
            "available"
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def name_link_or_nil(student)
        if student
            link_to student.name, user_path(student)
        else
            "none (yet)"
        end
    end
end

app/views/layouts/_instructor_dropdown.html.erb
<ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Lessons
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          
          <a class="dropdown-item" href="<%= lessons_path %>">Community Board</a>
          <a class="dropdown-item" href="<%= user_path(current_user) %>">My Lessons</a>
          <a class="dropdown-item" href="<%= user_lessons_path(current_user) %>">My Available Lessons</a>
          <div class="dropdown-divider"></div>
          <% if current_user.instructor %>
            <a class="dropdown-item" href="<%= new_user_lesson_path(current_user) %>">New Lesson</a>
          <% end %>
          
        </div>
      </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Jifunze</a>
  

  <% if user_is_authenticated %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_is_instructor %>
      <%= render "layouts/instructor_dropdown" %>
    <% else %>
      <%= render "layouts/student_dropdown" %>
    <% end %>
    
    <%= link_to "Log Out", logout_path, method: :post, class: "btn btn-outline-success" %>
    <%= link_to "physics lessons", "/lessons/physics", class: "btn btn-outline-success" %>
  </div>
  <% end %>
</nav>

app/views/layouts/_student_dropdown.html.erb
<ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Lessons
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= lessons_path %>">Community Board</a>
          <a class="dropdown-item" href="<%= user_path(current_user) %>">My Lessons</a>
        </div>
      </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jifunze</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<% if !@lesson.errors.messages.empty? %>
        <% @lesson.errors.full_messages.each do |e| %>
            <div class="alert alert-danger" role="alert">
                <%= e %>
            </div>
        <% end %>
<% end %>

<%= form_for @lesson do |f| %>

    <div class="form-row">
        <div class="col">
            <%= f.text_field :subject, class: "form-control", placeholder: "Subject" %>
        </div>
        <div class="col">
            <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
        </div>
    </div>
    <br>
    <div class="form-row">
        <div class="col">
            <%= f.datetime_field :time, class: "form-control datetimepicker-input"  %>
        </div>
        <div class="col">
            <%= f.number_field :duration, class: "form-control", placeholder: "Duration (in minutes)" %>
        </div>
    </div>
    <br>
    <div class="form-row">
        <div class="col">
            <%= f.text_area :notes, class: "form-control", placeholder: "Description (topics covered, grade level, materials required, etc.)", rows: "5" %>
        </div>
    </div>
    <br>
    <div class="form-row">
        <div class="col">
            <%= f.collection_select :student_id, User.students, :id, :name, {prompt: "Student (optional)"}, {class: "custom-select"} %>
        </div>
    </div>
    <br>
    <div class="form-row">
        <div class="col">
            <%= f.submit class: "btn btn-success" %>
        </div>
    </div>
<% end %>

app/views/lessons/edit.html.erb
<div class="container">
<br>
<h2>Edit Lesson</h2>
<br>
<%= render "form" %>
<br>
    <div class="form-row">
        <div class="col">
            <%= link_to "Delete Lesson", lesson_path(@lesson), method: "delete", class: "btn btn-danger" %>
        </div>
    </div>
</div>

app/views/lessons/index.html.erb
<% if @user %>
    <h2><%= @user.name %>'s Available Lesson Slots</h2>
<% else %>
    <h2>All Available Lessons</h2>
<% end %>

<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-center" scope="col">Subject</th>
            <th class="text-center" scope="col">Instructor</th>
            <th class="text-center" scope="col">Time</th>
            <th class="text-center" scope="col">Status</th>
            <th class="text-center" scope="col">Info</th>
        </tr>
    </thead>
    <tbody>
        <% @lessons.each do |l| %>
        <tr>
            <th class="text-center" scope="row"><%= l.subject %></th>
            <td class="text-center"><%= link_to l.instructor.name, user_lessons_path(l.instructor)%></td>
            <td class="text-center"><%= l.time.strftime("%A, %d %b %Y at %l:%M %p %Z") %></td>
            <td class="text-center"><h2><span class="badge badge-success"><%= status(l) %></span></h2></td>
            <td class="text-center"><%= link_to "tell me more", lesson_path(l), class: "btn btn-outline-success" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/lessons/new.html.erb
<div class="container">
<br>
<h2>New Lesson</h2>
<br>

<% if !@lesson.errors.messages.empty? %>
        <% @lesson.errors.full_messages.each do |e| %>
            <div class="alert alert-danger" role="alert">
                <%= e %>
            </div>
        <% end %>
<% end %>

<%= form_for @lesson do |f| %>

    <div class="form-row">
        <div class="col">
            <%= f.text_field :subject, class: "form-control", placeholder: "Subject" %>
        </div>
        <div class="col">
            <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
        </div>
    </div>
    <br>
    <div class="form-row">
        <div class="col">
            <%= f.datetime_field :time, class: "form-control datetimepicker-input"  %>
        </div>
        <div class="col">
            <%= f.number_field :duration, class: "form-control", placeholder: "Duration (in minutes)" %>
        </div>
    </div>
    <br>
    <div class="form-row">
        <div class="col">
            <%= f.text_area :notes, class: "form-control", placeholder: "Description (topics covered, grade level, materials required, etc.)", rows: "5" %>
        </div>
    </div>
    <br>
    <div class="form-row">
        <div class="col">
            <%= f.submit class: "btn btn-success" %>
        </div>
    </div>
<% end %>
</div>

app/views/lessons/physics.html.erb
<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-center" scope="col">Subject</th>
            <th class="text-center" scope="col">Instructor</th>
            <th class="text-center" scope="col">Time</th>
            <th class="text-center" scope="col">Status</th>
            <th class="text-center" scope="col">Info</th>
        </tr>
    </thead>
    <tbody>
        <% @lessons.each do |l| %>
        <tr>
            <th class="text-center" scope="row"><%= l.subject %></th>
            <td class="text-center"><%= link_to l.instructor.name, user_lessons_path(l.instructor)%></td>
            <td class="text-center"><%= l.time.strftime("%A, %d %b %Y at %l:%M %p %Z") %></td>
            <td class="text-center"><h2><span class="badge badge-success"><%= status(l) %></span></h2></td>
            <td class="text-center"><%= link_to "tell me more", lesson_path(l), class: "btn btn-outline-success" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/lessons/show.html.erb
<br>
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4"><%= @lesson.subject %> with <%= @lesson.instructor.name %> 
            <span class="badge badge-success"><%= status(@lesson) %></span>
        </h1>
        <p class="lead"><%= time_slot_display(@lesson) %>
        <br>
        @ <%= @lesson.location %>
        <% if @lesson.student %>
        <br>
        student: <%= name_link_or_nil(@lesson.student) %></p>
        <% end %>
        <hr class="my-4">
        <p><%= @lesson.notes %></p>
        <%= lesson_show_page_button(@lesson) %>
    </div>
</div>

app/views/session/new.html.erb
<br>
<div class="container">
    <h1>Log In</h1>

    <% if !@user.errors.messages.empty? %>
        <% @user.errors.full_messages.each do |e| %>
            <div class="alert alert-danger" role="alert">
                <%= e %>
            </div>
        <% end %>
    <% end %>

    <%= form_for @user, url: '/login', method: 'post' do |f| %>

        <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "username" %>
        </div>

        <div class="form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "password" %>
        </div>

        <%= f.submit class:"btn btn-outline-success", value: "Log In" %>
        
    <% end %>
</div>

app/views/users/_instructor_show.html.erb
<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-center" scope="col">Subject</th>
            <th class="text-center" scope="col">Student</th>
            <th class="text-center" scope="col">Time</th>
            <th class="text-center" scope="col">Status</th>
            <th class="text-center" scope="col">Info</th>
        </tr>
    </thead>
    <tbody>
        <% @user.given_lessons.each do |l| %>
        <tr>
            <th class="text-center" scope="row"><%= l.subject %></th>
            <td class="text-center"><%= name_link_or_nil(l.student) %></td>
            <td class="text-center"><%= l.time.strftime("%A, %d %b %Y at %l:%M %p %Z") %></td>
            <td class="text-center"><h2><span class="badge badge-success ba"><%= status(l) %></span></h2></td>
            <td class="text-center"><%= link_to "tell me more", lesson_path(l), class: "btn btn-outline-success" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/_student_show.html.erb
<table class="table table-hover">
    <thead>
        <tr>
            <th class="text-center" scope="col">Subject</th>
            <th class="text-center" scope="col">Instructor</th>
            <th class="text-center" scope="col">Time</th>
            <th class="text-center" scope="col">Status</th>
            <th class="text-center" scope="col">Info</th>
        </tr>
    </thead>
    <tbody>
        <% @user.taken_lessons.each do |l| %>
        <tr>
            <th class="text-center" scope="row"><%= l.subject %></th>
            <td class="text-center"><%= link_to l.instructor.name, user_lessons_path(l.instructor)%></td>
            <td class="text-center"><%= l.time.strftime("%A, %d %b %Y at %l:%M %p %Z") %></td>
            <td class="text-center"><h2><span class="badge badge-success ba"><%= status(l) %></span></h2></td>
            <td class="text-center"><%= link_to "tell me more", lesson_path(l), class: "btn btn-outline-success" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<br>
<div class="container">
    <h1>Let's get you signed up!</h1>

    <% if @user.errors %>
        <% @user.errors.full_messages.each do |e| %>
            <div class="alert alert-danger" role="alert">
                <%= e %>
            </div>
        <% end %>
    <% end %>

    <%= form_for @user, url: '/signup' do |f| %>
        <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "username" %>
        </div>
        
        <div class="form-group">
            <%= f.text_field :email, class: "form-control", placeholder: "email" %>
        </div>

        <div class="form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "password" %>
        </div>

        <div class="form-group form-check">
            <%= f.check_box :instructor, class: "form-check-input" %>
            <%= f.label :instructor, "check this box if you are a tutor", class: "form-check-label text-muted" %>
        </div>
        
        <%= f.submit class:"btn btn-outline-success", value: "Sign Up" %>
    <% end %>
</div>

app/views/users/show.html.erb
<h2><%= @user.name %>'s Lessons</h2>

<% if @user.student? %>
    <%= render "student_show" %>
<% else %>
    <%= render "instructor_show" %>
<% end %>

app/views/welcome/home.html.erb
<br>
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">Welcome to Jifunze!</h1>
    <p class="lead">"jifunze" means "learn" in Swahili. If you're a student looking for a tutor, or a tutor looking for students, you've come to the right place.</p>
    <hr class="my-4">
    <p>Enter any way you'd like.</p>
    
    
        <a id="sign-up" class="btn btn-outline-success" href="<%= signup_path %>" role="button">Sign Up</a>
      
        <a id="log-in" class="btn btn-outline-success" href="<%= login_path %>" role="button">Log In</a>
        <br><br>
        <a class="btn btn-outline-primary" href="/auth/facebook" role="button">Log In With Facebook<br><small class="form-text text-muted">(for students)</small></a>
        <br>
        
      
    
  </div>
</div>